name: Website

env:
  make: deploy
  GITHUB_REPOSITORY: driscollcode/nicole-carter-cleaning

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  publish:
    name: Website
    runs-on: ubuntu-18.04
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Install Github Access Token
        run: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Setup
        run: npm install
      - name: Github Credentials
        run: git config user.name "John Driscoll"; git config user.email "jddcode.github@jdd.email"
      - name: Deployment
        run: |
          git config user.name "John Driscoll"
          git config user.email "jddcode.github@jdd.email"
          git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git remote set-url origin "https://jddcode:${{ secrets.GH_TOKEN }}@github.com/driscollcode/nicole-carter-cleaning"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CI: false